name: Release Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        working-directory: viewer

    - name: Install dependencies
      run: npm install
      working-directory: viewer

    - name: Build application
      run: npm run build
      working-directory: viewer

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      working-directory: viewer
      with:
        name: build-artifact
        path: ./dist